// examples/vue-task-viewer/src/pages/TasksPage.vue
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue';
import {
  ElCard,
  ElTable,
  ElTableColumn,
  ElTag,
  ElButton,
  ElMessage,
  ElEmpty,
} from 'element-plus';
import { Refresh } from '@element-plus/icons-vue';
import { useAuthStore } from '@/stores/auth';
import { getMyPendingTasks, type BonitaTask } from '@/api/tasks';

const auth = useAuthStore();
const tasks = ref<BonitaTask[]>([]);
const total = ref(0);
const loading = ref(false);

const PRIORITY_COLOR: Record<string, 'success' | 'warning' | 'info' | 'primary' | 'danger'> = {
  highest: 'danger',
  above_normal: 'warning',
  normal: 'primary',
  under_normal: 'info',
  lowest: 'info',
};

async function load() {
  if (!auth.user) return;
  loading.value = true;
  try {
    const { data, total: t } = await getMyPendingTasks(auth.user.userId, 0, 50);
    tasks.value = data;
    total.value = t >= 0 ? t : data.length;
  } catch (e) {
    ElMessage.error(e instanceof Error ? e.message : 'Failed to load tasks');
  } finally {
    loading.value = false;
  }
}

function fmt(d?: string) {
  return d ? new Date(d).toLocaleString() : '—';
}

onMounted(load);
watch(() => auth.user?.userId, () => load());
</script>

<template>
  <ElCard>
    <template #header>
      <div class="card-header">
        <span class="title">
          My pending tasks
          <span class="count">({{ total }} total)</span>
        </span>
        <ElButton :icon="Refresh" :loading="loading" @click="load">Refresh</ElButton>
      </div>
    </template>

    <ElTable :data="tasks" v-loading="loading" stripe>
      <ElTableColumn label="Task">
        <template #default="{ row }">
          {{ row.displayName || row.name }}
        </template>
      </ElTableColumn>
      <ElTableColumn prop="priority" label="Priority" width="160">
        <template #default="{ row }">
          <ElTag :type="PRIORITY_COLOR[row.priority] ?? 'info'">{{ row.priority }}</ElTag>
        </template>
      </ElTableColumn>
      <ElTableColumn prop="caseId" label="Case" width="120" />
      <ElTableColumn label="Due" width="200">
        <template #default="{ row }">{{ fmt(row.dueDate) }}</template>
      </ElTableColumn>
      <template #empty>
        <ElEmpty description="No pending tasks" />
      </template>
    </ElTable>
  </ElCard>
</template>

<style scoped>
.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.title {
  font-size: 16px;
  font-weight: 600;
}
.count {
  font-weight: 400;
  color: #909399;
  margin-left: 8px;
}
</style>

// examples/angular-task-viewer/src/app/pages/tasks.page.ts
import { Component, computed, effect, inject, signal } from '@angular/core';
import { firstValueFrom } from 'rxjs';
import { AuthStore } from '../stores/auth.store';
import { TasksService, BonitaTask } from '../api/tasks.service';

const PRIORITY_COLOR: Record<string, string> = {
  highest: '#c0392b',
  above_normal: '#e67e22',
  normal: '#3498db',
  under_normal: '#16a085',
  lowest: '#7f8c8d',
};

@Component({
  selector: 'app-tasks',
  standalone: true,
  template: `
    <div class="card">
      <header class="card-header">
        <h2>
          My pending tasks
          <span class="count">({{ total() }} total)</span>
        </h2>
        <button class="refresh" [disabled]="loading()" (click)="load()">
          {{ loading() ? 'Loading...' : 'Refresh' }}
        </button>
      </header>

      @if (error()) {
        <p class="error">{{ error() }}</p>
      }

      @if (!loading() && tasks().length === 0) {
        <p class="empty">No pending tasks.</p>
      } @else {
        <table>
          <thead>
            <tr>
              <th>Task</th>
              <th class="priority-col">Priority</th>
              <th class="case-col">Case</th>
              <th class="due-col">Due</th>
            </tr>
          </thead>
          <tbody>
            @for (task of tasks(); track task.id) {
              <tr>
                <td>{{ task.displayName || task.name }}</td>
                <td>
                  <span class="badge" [style.background]="priorityColor(task.priority)">
                    {{ task.priority }}
                  </span>
                </td>
                <td>{{ task.caseId }}</td>
                <td>{{ formatDate(task.dueDate) }}</td>
              </tr>
            }
          </tbody>
        </table>
      }
    </div>
  `,
  styles: [`
    .card {
      background: white;
      border-radius: 8px;
      padding: 24px;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.04);
    }
    .card-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-bottom: 16px;
    }
    h2 { margin: 0; font-size: 18px; font-weight: 600; }
    .count { color: #909399; font-weight: 400; margin-left: 8px; font-size: 14px; }
    .refresh {
      padding: 8px 16px;
      background: var(--color-primary, #dd0031);
      color: white;
      border: none;
      border-radius: 4px;
    }
    .error { color: #c00; }
    .empty { color: #909399; padding: 24px; text-align: center; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 10px 12px; text-align: left; border-bottom: 1px solid var(--color-border, #e4e7ed); }
    th { font-weight: 600; font-size: 13px; color: #606266; background: #fafafa; }
    .priority-col { width: 140px; }
    .case-col { width: 120px; }
    .due-col { width: 200px; }
    .badge {
      display: inline-block;
      padding: 2px 10px;
      border-radius: 10px;
      color: white;
      font-size: 12px;
      font-weight: 500;
    }
  `],
})
export class TasksPage {
  private store = inject(AuthStore);
  private tasksService = inject(TasksService);

  tasks = signal<BonitaTask[]>([]);
  total = signal(0);
  loading = signal(false);
  error = signal<string | null>(null);

  private userId = computed(() => this.store.user()?.userId);

  constructor() {
    effect(() => {
      const id = this.userId();
      if (id) this.load();
    });
  }

  async load() {
    const id = this.userId();
    if (!id) return;
    this.loading.set(true);
    this.error.set(null);
    try {
      const { data, total } = await firstValueFrom(
        this.tasksService.getMyPendingTasks(id, 0, 50)
      );
      this.tasks.set(data);
      this.total.set(total);
    } catch (e) {
      this.error.set(e instanceof Error ? e.message : 'Failed to load tasks');
    } finally {
      this.loading.set(false);
    }
  }

  priorityColor(p: string): string {
    return PRIORITY_COLOR[p] ?? '#909399';
  }

  formatDate(d?: string): string {
    return d ? new Date(d).toLocaleString() : '—';
  }
}
