// templates/solid-vite-bonita/src/App.tsx
import { Show, createSignal, onMount, type ParentProps } from 'solid-js';
import { useNavigate, useLocation } from '@solidjs/router';
import { authStore } from './stores/auth';
import { setSessionExpiredHandler } from './api/client';

export default function App(props: ParentProps) {
  const navigate = useNavigate();
  const location = useLocation();
  const [booted, setBooted] = createSignal(false);

  onMount(async () => {
    setSessionExpiredHandler(() => {
      authStore.clearUser();
      navigate('/login', { replace: true });
    });
    await authStore.loadSession();
    setBooted(true);
    if (!authStore.isAuthenticated && location.pathname !== '/login') {
      navigate('/login', { replace: true });
    }
  });

  const onLogout = async () => {
    await authStore.logoutAndClear();
    navigate('/login', { replace: true });
  };

  return (
    <Show
      when={booted()}
      fallback={<div class="booting">Loading…</div>}
    >
      <Show
        when={authStore.isAuthenticated && location.pathname !== '/login'}
        fallback={<>{props.children}</>}
      >
        <div class="layout">
          <header class="topbar">
            <h1>__DISPLAY_NAME__</h1>
            <div class="actions">
              <span class="user">{authStore.user?.displayName}</span>
              <button class="logout" onClick={onLogout}>Logout</button>
            </div>
          </header>
          <main class="content">{props.children}</main>
        </div>
      </Show>
    </Show>
  );
}

// templates/svelte-vite-bonita/src/App.svelte
<script lang="ts">
  import Router, { push } from 'svelte-spa-router';
  import { onMount } from 'svelte';
  import LoginPage from './lib/pages/LoginPage.svelte';
  import Layout from './lib/pages/Layout.svelte';
  import { authStore } from './lib/stores/auth.svelte';
  import { setSessionExpiredHandler } from './lib/api/client';

  const routes = {
    '/login': LoginPage,
    '*': Layout,
  };

  let booting = $state(true);

  onMount(async () => {
    setSessionExpiredHandler(() => {
      authStore.clearUser();
      push('/login');
    });
    await authStore.loadSession();
    booting = false;
    if (!authStore.isAuthenticated && !location.hash.startsWith('#/login')) {
      push('/login');
    }
  });
</script>

{#if booting}
  <div class="booting">
    <p>Loading…</p>
  </div>
{:else}
  <Router {routes} />
{/if}

<style>
  .booting {
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100dvh;
    color: #909399;
  }
</style>
