// templates/solid-vite-bonita/src/pages/LoginPage.tsx
import { createSignal, Show, createEffect } from 'solid-js';
import { useNavigate, useSearchParams } from '@solidjs/router';
import { login, getSession } from '../api/auth';
import { authStore } from '../stores/auth';

export default function LoginPage() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [username, setUsername] = createSignal('');
  const [password, setPassword] = createSignal('');
  const [loading, setLoading] = createSignal(false);
  const [error, setError] = createSignal<string | null>(null);

  createEffect(() => {
    if (authStore.isAuthenticated) {
      const redirect = (searchParams.redirect as string) || '/';
      navigate(redirect, { replace: true });
    }
  });

  const onSubmit = async (e: Event) => {
    e.preventDefault();
    if (!username() || !password()) return;
    setLoading(true);
    setError(null);
    try {
      await login(username(), password());
      const s = await getSession();
      authStore.setUserFromSession(s);
      navigate('/', { replace: true });
    } catch {
      setError('Invalid credentials');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div class="wrapper">
      <form class="card" onSubmit={onSubmit}>
        <h1>Sign in</h1>
        <input
          type="text"
          placeholder="Username"
          autocomplete="username"
          value={username()}
          onInput={(e) => setUsername(e.currentTarget.value)}
          required
        />
        <input
          type="password"
          placeholder="Password"
          autocomplete="current-password"
          value={password()}
          onInput={(e) => setPassword(e.currentTarget.value)}
          required
        />
        <Show when={error()}>
          <p class="error">{error()}</p>
        </Show>
        <button type="submit" disabled={loading()}>
          {loading() ? 'Signing in…' : 'Sign in'}
        </button>
      </form>

      <style>{`
        .wrapper { display:flex; justify-content:center; align-items:center; min-height:100dvh; background: var(--color-bg); }
        .card { width:320px; padding:32px; background:white; border-radius:8px; box-shadow:0 4px 24px rgba(0,0,0,0.06); display:flex; flex-direction:column; gap:12px; }
        h1 { margin:0 0 8px; text-align:center; }
        input { padding:10px 12px; border:1px solid var(--color-border); border-radius:4px; font:inherit; }
        input:focus { outline:2px solid var(--color-primary); outline-offset:-1px; }
        button { padding:10px; background: var(--color-primary); color:white; border:none; border-radius:4px; }
        .error { color:#c00; margin:0; font-size:14px; }
      `}</style>
    </div>
  );
}

// templates/vue-vite-bonita/src/pages/LoginPage.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { ElForm, ElFormItem, ElInput, ElButton, ElCard, ElMessage } from 'element-plus';
import { User, Lock } from '@element-plus/icons-vue';
import { login, getSession } from '@/api/auth';
import { useAuthStore } from '@/stores/auth';

const router = useRouter();
const route = useRoute();
const auth = useAuthStore();

const username = ref('');
const password = ref('');
const loading = ref(false);

async function onSubmit() {
  if (!username.value || !password.value) return;
  loading.value = true;
  try {
    await login(username.value, password.value);
    const s = await getSession();
    auth.setUserFromSession(s);
    const redirect = (route.query.redirect as string) || '/';
    router.replace(redirect);
  } catch {
    ElMessage.error('Invalid credentials');
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div class="login-wrapper">
    <ElCard class="login-card" shadow="hover">
      <h2 class="title">Sign in</h2>
      <ElForm @submit.prevent="onSubmit" label-position="top">
        <ElFormItem>
          <ElInput v-model="username" placeholder="Username" autocomplete="username" :prefix-icon="User" />
        </ElFormItem>
        <ElFormItem>
          <ElInput
            v-model="password"
            type="password"
            placeholder="Password"
            autocomplete="current-password"
            :prefix-icon="Lock"
            show-password
          />
        </ElFormItem>
        <ElButton type="primary" native-type="submit" :loading="loading" style="width: 100%">
          Sign in
        </ElButton>
      </ElForm>
    </ElCard>
  </div>
</template>

<style scoped>
.login-wrapper {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100dvh;
  background: #f3f3f1;
}
.login-card {
  width: 360px;
}
.title {
  text-align: center;
  margin: 0 0 16px;
  color: #303133;
}
</style>
