// examples/solid-directory-bonita/src/pages/LoginPage.tsx
import { createSignal, Show, createEffect } from 'solid-js';
import { useNavigate, useSearchParams } from '@solidjs/router';
import { login, getSession } from '../api/auth';
import { authStore } from '../stores/auth';

export default function LoginPage() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [username, setUsername] = createSignal('');
  const [password, setPassword] = createSignal('');
  const [loading, setLoading] = createSignal(false);
  const [error, setError] = createSignal<string | null>(null);

  createEffect(() => {
    if (authStore.isAuthenticated) {
      const redirect = (searchParams.redirect as string) || '/';
      navigate(redirect, { replace: true });
    }
  });

  const onSubmit = async (e: Event) => {
    e.preventDefault();
    if (!username() || !password()) return;
    setLoading(true);
    setError(null);
    try {
      await login(username(), password());
      const s = await getSession();
      authStore.setUserFromSession(s);
      navigate('/', { replace: true });
    } catch {
      setError('Invalid credentials');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div class="login-wrapper">
      <form class="login-card" onSubmit={onSubmit}>
        <h1>Sign in</h1>
        <input
          type="text"
          placeholder="Username"
          autocomplete="username"
          value={username()}
          onInput={(e) => setUsername(e.currentTarget.value)}
          required
        />
        <input
          type="password"
          placeholder="Password"
          autocomplete="current-password"
          value={password()}
          onInput={(e) => setPassword(e.currentTarget.value)}
          required
        />
        <Show when={error()}>
          <p class="error">{error()}</p>
        </Show>
        <button type="submit" disabled={loading()}>
          {loading() ? 'Signing in…' : 'Sign in'}
        </button>
      </form>
    </div>
  );
}

// examples/react-task-viewer/src/pages/LoginPage.tsx
import { useState } from 'react';
import { useNavigate, Navigate } from 'react-router-dom';
import { Form, Input, Button, Card, Typography, App } from 'antd';
import { UserOutlined, LockOutlined } from '@ant-design/icons';
import { login, getSession } from '../api/auth';
import { useAuthStore } from '../stores/authStore';

const { Title } = Typography;

export const LoginPage = () => {
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const setUser = useAuthStore((s) => s.setUser);
  const isAuthenticated = useAuthStore((s) => s.isAuthenticated);
  const isLoading = useAuthStore((s) => s.isLoading);
  const { message } = App.useApp();

  if (!isLoading && isAuthenticated) {
    return <Navigate to="/" replace />;
  }

  const onFinish = async (values: { username: string; password: string }) => {
    setLoading(true);
    try {
      await login(values.username, values.password);
      const s = await getSession();
      setUser({
        userId: s.user_id,
        userName: s.user_name,
        displayName: s.user_name,
        isTechnicalUser: s.is_technical_user,
      });
      navigate('/');
    } catch {
      message.error('Invalid credentials');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div
      style={{
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        minHeight: '100dvh',
        background: '#F3F3F1',
      }}
    >
      <Card style={{ width: 360 }}>
        <Title level={3} style={{ textAlign: 'center', marginBottom: 24 }}>
          Sign in
        </Title>
        <Form layout="vertical" onFinish={onFinish}>
          <Form.Item name="username" rules={[{ required: true, message: 'Username required' }]}>
            <Input prefix={<UserOutlined />} placeholder="Username" autoComplete="username" />
          </Form.Item>
          <Form.Item name="password" rules={[{ required: true, message: 'Password required' }]}>
            <Input.Password prefix={<LockOutlined />} placeholder="Password" autoComplete="current-password" />
          </Form.Item>
          <Button type="primary" htmlType="submit" loading={loading} block>
            Sign in
          </Button>
        </Form>
      </Card>
    </div>
  );
};
